<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Myapp</title>
    </head>
    <body>
        <h2> Contact </h2>
        
        <?php
            if ($contact->row) {
                echo "<table>
                    <tr><th>Id</th><th>Name</th><th>Email</th></tr>";
                echo "<tr><td>". $contact->row['id']."<td>".$contact->row['name']."</td>"
                ."<td>".$contact->row['email']."</td></tr> </table>";
            } else {
                echo "No contact found with Id=";
                if (isset($_GET['id'])) {
                    echo $_GET['id'];
                }
            }
        ?>
    </body>
</html>
